LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_CERTIFICATE := media
LOCAL_MODULE := KDDI_OneSeg
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := KDDI_OneSeg
LOCAL_SRC_FILES := KDDI_OneSeg.apk

include $(BUILD_PREBUILT)

